# Generated by Django 5.2.9 on 2026-01-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chatsession_options_chatsession_is_pinned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
